name: personal_budget
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  sqflite: 1.1.3
  path: 1.6.2
  cupertino_icons: ^0.1.2
  equatable: ^0.2.0
  datetime_picker_formfield: 0.1.8
  flutter_bloc: ^0.7.0
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ">=1.3.0 <2.0.0"
  mockito: 4.0.0
  pedantic: ^1.4.0

flutter:

  uses-material-design: true